### ISSUE TITLE
remove references to steps_per_epochs and fit_genrator from keras_sequential_api_vertex notebook

### ISSUE THREAD

**Issue by sanjanalreddy** [GoogleCloudPlatform/asl-ml-immersion#248]

**Comment by takumiohym** [comment]
Removed `fit_generator` in #267, but why removing `steps_per_epoch` as well?
(I agree if it is just for simplicity.) @sanjanalreddy

**Comment by sanjanalreddy** [comment]
@takumiohym we have removed the argument `steps_per_epoch` in the `.fit` method but the markdown still read "The steps_per_epoch parameter is used to mark the end of training for a single epoch. Here we are training for NUM_EVALS epochs. Lastly, for the callback argument we specify a Tensorboard callback so we can inspect Tensorboard after training."

This is what the `.fit` method looks like:
```
%time

LOGDIR = "./taxi_trained"
history = model.fit(
    x=trainds,
    epochs=10,
    validation_data=evalds,
    callbacks=[TensorBoard(LOGDIR)],
)
```

Either we update the `.fit` method or we add the `steps_per_epoch` argument back.

**Comment by takumiohym** [comment]
@sanjanalreddy Oh thanks!
I opened the PR for it. #275 . Please check and merge it.
