### ISSUE TITLE
add model deployment to vertex ai to keras_for_text_classification

### ISSUE THREAD

**Issue by sanjanalreddy** [GoogleCloudPlatform/asl-ml-immersion#250]
With the introduction of preprocessing layers, we can directly pass raw input to the model. We should add Vertex AI model deployment code to show how to upload a text model to Vertex. The NB has three models, we can choose to deploy one of the models to Vertex.

**Comment by pandyaved98** [comment]
Hello Sanjana, Greeting!

Assign this issue to me, I will try my best to work on this.

**Comment by sanjanalreddy** [comment]
@pandyaved98 Thank you for your interest. Unfortunately, we are not taking any external contributions to this repo.
