### ISSUE TITLE
Module Updates 202212

### ISSUE THREAD

**Issue by takumiohym** [GoogleCloudPlatform/asl-ml-immersion#278]
## Overview
Update modules for ASL training environment.

## Target Modules
- tensorflow
  - 2.6.5 -> [2.8.3](https://github.com/tensorflow/tensorflow/releases/tag/v2.8.3) (Supported on Vertex AI Workbench TensorFlow Enterprise with LTS, released on 2022/09/02)
- tfx
  - 1.4.0 -> [1.8.1](https://github.com/tensorflow/tfx/releases/tag/v1.8.1) (Latest version compatible with TF2.8, released on 2022/08/01) 
- kfp
  - 1.8.10 -> [1.8.16](https://github.com/kubeflow/pipelines/releases/tag/1.8.16) (Latest as of 2022/11/24) 
- google-cloud-aiplatform 
  - 1.7.1 -> [1.19.0](https://github.com/googleapis/python-aiplatform/releases/tag/v1.19.0) (Latest as of 2022/11/24) 
- google-cloud-pipeline-components
  - 0.2.1 -> [1.0.27](https://pypi.org/project/google-cloud-pipeline-components/1.0.27/) (Latest as of 2022/11/24) 

Details are in PR #277 

## Dev Branch
**[dev_module_update_202212](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212)**

## Test Tracker

- [x] [bigquery](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/bigquery)  @kylesteckler 
- [x] [building_production_ml_systems](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/building_production_ml_systems) @sanjanalreddy 
- [x] [docker_and_kubernetes](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/docker_and_kubernetes) @BenoitDherin 
- [x] [end-to-end-structured](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/end-to-end-structured) @BenoitDherin 
- [x] [feature_engineering](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/feature_engineering) @BenoitDherin 
- [x] [image_models](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/image_models) @takumiohym 
- [x] [introduction_to_tensorflow](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/introduction_to_tensorflow) @takumiohym
- (Skipped) [jax](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/jax) (Need maintenance? Skip so far?)
- [x] [kubeflow_pipelines](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/kubeflow_pipelines) @takumiohym 
- [x] [launching_into_ml](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/launching_into_ml) @sanjanalreddy 
- [x] [ml_fairness_explainability](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/ml_fairness_explainability) @kylesteckler 
- [x] [model_monitoring](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/model_monitoring) @kylesteckler 
- [x] [multi_modal](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/multi_modal) @takumiohym 
- [x] [recommendation_systems](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/recommendation_systems) @takumiohym 
- [x] [reinforcement_learning](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/reinforcement_learning) @BenoitDherin 
- (Skipped) [supplemental](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/supplemental) (Remove?)
- [x] [text_models](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/text_models) @sanjanalreddy 
- [x] [tfx_pipelines](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/tfx_pipelines) @kylesteckler 
- [x] [time_series_prediction](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/time_series_prediction) @sanjanalreddy 
- [x] [uncertainty_aware_models](https://github.com/GoogleCloudPlatform/asl-ml-immersion/tree/dev_module_update_202212/notebooks/uncertainty_aware_models) @BenoitDherin

**Comment by sanjanalreddy** [comment]
Added myself to a few  modules

**Comment by takumiohym** [comment]
Thanks @kylesteckler @sanjanalreddy @BenoitDherin! All the tests and updates are done.

Here is the summary of the update.

## Results ([all PRs](https://github.com/GoogleCloudPlatform/asl-ml-immersion/pulls?q=is%3Apr+label%3A%22Module+Update%3A+2022%2F12%22))
- 5 Minor updates
- Removed 2 labs
  - [building_production_ml_systems/…/3_kubeflow_pipelines_vertex.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/298)
    - Too old, not used, standard KFP modules cover it better.
  - [ml_fairness_explainability/…/1_inclusive_ml.ipynb](https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/297)
    - LIT is available, the same demo is available on the official web, not compatible with Vertex AI Workbench User Managed Notebooks
- Moved 3 labs to special kernels
  - [Reinforcement Learning module](https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/288)
  - [Reliable ML module](https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/295)
  - [TF Recommenders lab](https://github.com/GoogleCloudPlatform/asl-ml-immersion/pull/290)
