### ISSUE TITLE
Missing service account error during setup_on_cloudshell.sh

### ISSUE THREAD

**Issue by ewall** [GoogleCloudPlatform/asl-ml-immersion#357]
This is a small issue with the initial environment setup with `./scripts/setup_on_cloudshell.sh`: by default, GCP does not have the Cloud Build API enabled, so the Cloud Build service account may not exist yet.

Thus, [line 21](https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/a228fbc98882d5b1ada057c0f828ee85e17e0899/scripts/setup_on_cloudshell.sh#L21), which attempts to grant a role on that service, will fail with an error message like, _"ERROR: (gcloud.projects.add-iam-policy-binding) INVALID_ARGUMENT: Service account ##########@cloudbuild.gserviceaccount.com does not exist."_

Hopefully the solution should be as simple as adding the following command before line 21:
`gcloud services enable cloudbuild.googleapis.com`

(I would create the pull request myself, but external contributions are not being accepted right now. 😉)

**Comment by bigfleet** [comment]
Another alternative is to leverage the `scripts/setup_on_jupyterlab.sh` script already written.  Then the only requirement might be for a small amendment to the `README.md` addressed at a 'new' audience that may need to ensure their account/project has the correct APIs enabled.

**Comment by takumiohym** [comment]
Thanks @ewall and @bigfleet .
That enablement command is already included in the Makefile, and the instruction is also included in the README.md.
Hope it helps!

https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/Makefile
https://github.com/GoogleCloudPlatform/asl-ml-immersion/blob/master/README.md
