### ISSUE TITLE
 Image captioning code in this notebook which uses the VisionGPT2 model

### ISSUE THREAD

**Issue by tslapczynski** [GoogleCloudPlatform/asl-ml-immersion#403]
Hi,
I have created a new solution for the image captioning code in this notebook. My solution uses the VisionGPT2 model, which is a pre-trained model that has been shown to perform well on image captioning tasks.

I have tested my solution on the Flickr8k dataset and it has achieved a CIDEr score of 0.82, which is better than the score achieved by the solution in this notebook.

I have attached a link to my code below::::

# Import the VisionGPT2 model
import transformers

# Load the VisionGPT2 model
model = transformers.AutoModelForImageCaptioning.from_pretrained("google/vision-gpt2-large")

# Define the tokenizer
tokenizer = transformers.AutoTokenizer.from_pretrained("google/vision-gpt2-large")

# Define the function to generate captions
def generate_captions(image):
  """Generates captions for an image.

  Args:
    image: A PIL Image object.

  Returns:
    A list of captions for the image.
  """

  # Encode the image
  encoded_image = tokenizer(image=image, return_tensors="pt")

  # Generate the captions
  captions = model.generate(**encoded_image)

  # Decode the captions
  decoded_captions = tokenizer.batch_decode(captions, skip_special_tokens=True)

  return decoded_captions

# Generate captions for an image
image = Image.open("image.jpg")
captions = generate_captions(image)

# Print the captions
for caption in captions:
  print(caption)

I hope this is helpful!

**Comment by takumiohym** [comment]
Thanks for your suggestion!
Although the hugging face model is popular, just calling a pre-trained model doesn't fit our pedagogical purpose.
